### ISSUE TITLE
AndroidContext not working v0.3.0

### ISSUE THREAD

**Issue by 5ach-in** [buijs-dev/klutter#22]
I believe you forgot to change `KlutterAdaptee` in `ADAPTEE_REGEX` to `Event` in `packages/core/src/main/kotlin/dev/buijs/klutter/core/shared/Method.kt`

I'm not 100% sure if that definitely is the cause of the issue, but when following the https://buijs.dev/klutter-2/ guide with `Android Studio Giraffe | 2022.3.1` and `klutter: 0.3.0`, when I run `./gradlew clean build -p "platform"` it just doesn't generate the methods annotated with `@AndroidContext`

`@AndroidContext` works for `klutter: 0.2.3` but that version doesn't generate the correct code for iOS in `BatterylevelPlugin.swift`

---
Also to get it building for Android with 0.3.0, I had to:
1) Update: `compileSdkVersion 34` & `targetSdkVersion 34` in `/batterylevel/android/build.gradle` and `/batterylevel/example/android/app/build.gradle`
2) Add: `maven { url = uri("https://storage.googleapis.com/download.flutter.io") }`
     and 
```gradle
implementation "dev.buijs.klutter:flutter-engine-kmp-android:2023.1.1.beta"
implementation "io.flutter:flutter_embedding_debug:1.0.0-bd539267b42051b0da3d16ffa8f48949dce8aa8f"
//(to get the long string at the end I used the ETAG from here: http://download.flutter.io/)
```
into `/batterylevel/android/build.gradle`
...
So I think some scripts need to be updated too please

---
```cmd
flutter --version
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (7 days ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0
```
---
My root YAML file looks like:
```yaml
name: batterylevel
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  klutter: 0.3.0
  #klutter_ui: ^0.0.3
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
```

---
Please let me know if you need me to provide any more info, thanks :)
